name: TCHangRail
main: com.bergerkiller.bukkit.hangrail.TCHangRail
api-version: 1.13
version: ${project.version}
authors: [bergerkiller]
description: Add-on for TrainCarts that allows specific Blocks to perform certain actions
depend: [Train_Carts]
metrics: true
dev-url: ${project.url}